name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run check
